server:
  port: 8080

spring:
  application:
    name: apexmatch-gateway

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    com.apexmatch: INFO
    org.springframework.web.socket: INFO
